# Generated by Django 5.2.6 on 2025-09-25 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('BLOG', 'New blog posts'), ('ANNOUNCEMENT', 'New announcement'), ('EVENT_REMINDER', 'Event reminders')], max_length=20)),
                ('enabled', models.BooleanField(default=False)),
            ],
        ),
    ]
