# Generated by Django 5.2.6 on 2025-10-13 06:09

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NotificationPreferences',
            new_name='NotificationPreference',
        ),
    ]
