# Generated by Django 5.2.6 on 2025-09-26 01:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='person',
        ),
        migrations.RemoveField(
            model_name='racer',
            name='person',
        ),
        migrations.AddField(
            model_name='racer',
            name='first_name',
            field=models.CharField(default='default', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='racer',
            name='last_name',
            field=models.CharField(default='default_last', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='racer',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user', to='users.racer'),
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
