# Generated by Django 5.2.6 on 2025-09-25 20:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='result',
            name='racer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.racer'),
        ),
    ]
