# Generated by Django 5.2.6 on 2025-10-30 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_alter_result_race'),
    ]

    operations = [
        migrations.AlterField(
            model_name='race',
            name='type',
            field=models.CharField(choices=[('SLALOM', 'Slalom'), ('COURSE', 'Course'), ('MARATHON', 'Marathon')], max_length=15),
        ),
    ]
