# Generated by Django 5.2.6 on 2025-10-30 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_alter_race_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='race',
            name='type',
            field=models.CharField(choices=[('SLALOM', 'Slalom'), ('COURSE', 'Course'), ('MARATHON', 'Marathon')], default='COURSE', max_length=15),
        ),
    ]
