# Generated by Django 5.2.6 on 2025-10-15 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventphoto',
            name='photo',
            field=models.ImageField(height_field='height', unique=True, upload_to='event_photos/', width_field='width'),
        ),
    ]
