# Generated by Django 5.2.6 on 2025-10-15 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_alter_eventphoto_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventphoto',
            name='height',
            field=models.PositiveSmallIntegerField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventphoto',
            name='width',
            field=models.PositiveSmallIntegerField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
