# Generated by Django 5.2.6 on 2025-10-24 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_event_entry_fee_alter_result_position'),
        ('photos', '0003_eventphoto_height_eventphoto_width'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventphoto',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='events.event'),
        ),
    ]
