# Generated by Django 5.2.6 on 2025-11-07 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0004_alter_eventphoto_event'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventphoto',
            old_name='poster',
            new_name='user',
        ),
    ]
